const studentsData = [
    {
        id: 1,
        name: "Aoyama Yuga",
        alias: "Can't Stop Twinkling",
        class: "1-A",
        quirk: "Navel Laser",
        birthday: "May 30",
        gender: "Male",
        fightingStyle: "Long Range Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/7/70/Yuga_Aoyama_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/4/45/Yuga_Aoyama_full_body_uniform.png/",
        color: "#F8F164"
    },
    {
        id: 2,
        name: "Ashido Mina",
        alias: "Alien Queen",
        class: "1-A",
        quirk: "Acid",
        birthday: "July 30",
        gender: "Female",
        fightingStyle: "Medium Range Support",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/89/Mina_Ashido_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/4/4e/Mina_Ashido_Full_Body_School_Uniform.png/",
        color: "#CB56BB"
    },
    {
        id: 3,
        name: "Asui Tsuyu",
        alias: "Froppy",
        class: "1-A",
        quirk: "Frog",
        birthday: "February 12",
        gender: "Female",
        fightingStyle: "Melee + Support Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/4/40/Tsuyu_Asui_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/f/ff/Tsuyu_Asui_Full_Body_School_Uniform_Anime.png/",
        color: "#36DB65"
    },
    {
        id: 4,
        name: "Iida Tenya",
        alias: "Ingenium",
        class: "1-A",
        quirk: "Engine",
        birthday: "August 22",
        gender: "Male",
        fightingStyle: "Close Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/12/Tenya_Iida_Full_Body_Hero_Costume_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/10/Tenya_Iida_Full_Body_School_Uniform.png/",
        color: "#113FD4"
    },
    {
        id: 5,
        name: "Uraraka Ochako",
        alias: "Uravity",
        class: "1-A",
        quirk: "Zero Gravity",
        birthday: "December 27",
        gender: "Female",
        fightingStyle: "Melee + Support Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/b/b3/Ochaco_Uraraka_Hero_Costume_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/6/69/Ochaco_School_Uniform_Full_Body.png/",
        color: "#F55CDD"
    },
    {
        id: 6,
        name: "Ojiro Mashirao",
        alias: "Tailman",
        class: "1-A",
        quirk: "Tail",
        birthday: "May 28",
        gender: "Male",
        fightingStyle: "Melee Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/9/95/Mashirao_Ojiro_Hero_Costume_2_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/0/09/Mashirao_Ojiro_Full_Body_Uniform.png/",
        color: "#E3E1E2"
    },
    {
        id: 7,
        name: "Kaminari Denki",
        alias: "Chargebolt",
        class: "1-A",
        quirk: "Electrification",
        birthday: "June 29",
        gender: "Male",
        fightingStyle: "Melee + Support Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/5/5f/Denki_Kaminari_2nd_Hero_Costume_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/b/bb/Denki_Kaminari.png/",
        color: "#C5BB24"
    },
    {
        id: 8,
        name: "Kirishima Eijiro",
        alias: "Red Riot",
        class: "1-A",
        quirk: "Hardening",
        birthday: "October 16",
        gender: "Male",
        fightingStyle: "Close Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/d/d5/Eijiro_Kirishima_3rd_Hero_Costume_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/3/3a/Eijiro_Kirishima_Student_Uniform_Profile.png/",
        color: "#F61115"
    },
    {
        id: 9,
        name: "Koda Koji",
        alias: "Anima",
        class: "1-A",
        quirk: "Anivoice",
        birthday: "February 1",
        gender: "Male",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/f/f4/Koji_Koda_Hero_Costume_2_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/2/20/Koji_Koda_Full_Body_Uniform.png/",
        color: "#E7B14B"
    },
    {
        id: 10,
        name: "Sato Rikido",
        alias: "Sugarman",
        class: "1-A",
        quirk: "Sugar Rush",
        birthday: "June 19",
        gender: "Male",
        fightingStyle: "Close Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/a/a0/Rikido_Sato_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/c/c9/Rikido_Sato_Full_Body_Uniform.png/",
        color: "#F0E599"
    },
    {
        id: 11,
        name: "Shoji Mezo",
        alias: "Tentacole",
        class: "1-A",
        quirk: "Dupli-Arms",
        birthday: "February 15",
        gender: "Male",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/2/20/Mezo_Shoji_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/5/55/Mezo_Shoji_Full_Body_Uniform.png/",
        color: "#2D2474"
    },
    {
        id: 12,
        name: "Jiro Kyoka",
        alias: "Earphone Jack",
        class: "1-A",
        quirk: "Earphone Jack",
        birthday: "August 1",
        gender: "Female",
        fightingStyle: "Medium Range Support",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/0/04/Kyoka_Jiro_Hero_Costume_2_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/8c/Kyoka_Jiro_Full_Body_Uniform.png/",
        color: "#4F4F4F"
    },
    {
        id: 13,
        name: "Sero Hanta",
        alias: "Cellophane",
        class: "1-A",
        quirk: "Tape",
        birthday: "July 28",
        gender: "Male",
        fightingStyle: "Ranged + Support Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/b/b3/Hanta_Sero_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/6/6c/Hanta_Sero_Full_Body_Uniform.png/",
        color: "#EAA53D"
    },
    {
        id: 14,
        name: "Tokoyami Fumikage",
        alias: "Tsukuyomi",
        class: "1-A",
        quirk: "Dark Shadow",
        birthday: "October 30",
        gender: "Male",
        fightingStyle: "Melee Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/a/ae/Fumikage_Tokoyami_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/b/ba/Fumikage_Tokoyami_Uniform.png/",
        color: "#444267"
    },
    {
        id: 15,
        name: "Todoroki Shoto",
        alias: "Shoto",
        class: "1-A",
        quirk: "Half-Cold Half-Hot",
        birthday: "January 11",
        gender: "Male",
        fightingStyle: "Ranged Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/b/b3/Shoto_Todoroki_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/c/c4/Shoto_Todoroki_school_profile.png/",
        color: "#48E0E6"
    },
    {
        id: 16,
        name: "Hagakure Toru",
        alias: "Invisible Girl",
        class: "1-A",
        quirk: "Invisibility",
        birthday: "June 16",
        gender: "Female",
        fightingStyle: "Melee + Support Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/a/a0/Toru_Hagakure_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/8f/Toru_Hagakure_Full_Body_Uniform.png/",
        color: "#88E4F9"
    },
    {
        id: 17,
        name: "Bakugo Katsuki",
        alias: "Kacchan",
        class: "1-A",
        quirk: "Explosion",
        birthday: "April 20",
        gender: "Male",
        fightingStyle: "Melee + Ranged Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/5/50/Katsuki_Bakugo_Hero_Costume_Action_Pose.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/83/Katsuki_Bakugo_School_Uniform_Full_Body.png/",
        color: "#D35311"
    },
    {
        id: 18,
        name: "Midoriya Izuku",
        alias: "Deku",
        class: "1-A",
        quirk: "One For All",
        birthday: "July 15",
        gender: "Male",
        fightingStyle: "Melee Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/f/f7/Izuku_Midoriya_Hero_Costume_Action_Pose.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/d/d9/Izuku_Midoriya_school_profile.png/",
        color: "#07915E"
    },
    {
        id: 19,
        name: "Mineta Minoru",
        alias: "Grape Juice",
        class: "1-A",
        quirk: "Pop Off",
        birthday: "October 8",
        gender: "Male",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/4/41/Minoru_Mineta_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/6/66/Minoru_Mineta_Full_Body_School_Uniform_Anime.png/",
        color: "#AF2AA0"
    },
    {
        id: 20,
        name: "Yaoyorozu Momo",
        alias: "Creati",
        class: "1-A",
        quirk: "Creation",
        birthday: "September 23",
        gender: "Female",
        fightingStyle: "Melee + Support Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/a/ac/Momo_Yaoyorozu_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/e/eb/Momo_Yaoyorozu_Full_Body_School_Uniform.png/",
        color: "#C00751"
    },
    {
        id: 21,
        name: "Awase Yosetsu",
        alias: "Welder",
        class: "1-B",
        quirk: "Weld",
        birthday: "November 7",
        gender: "Male",
        fightingStyle: "Support Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/c/c4/Yosetsu_Awase_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/c/c4/Yosetsu_Awase_Anime_Profile.png/",
        color: "#3C5FAA"
    },
    {
        id: 22,
        name: "Kaibara Sen",
        alias: "Spiral",
        class: "1-B",
        quirk: "Gyrate",
        birthday: "June 12",
        gender: "Male",
        fightingStyle: "Close Range Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/1e/Sen_Kaibara_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/1e/Sen_Kaibara_Anime_Profile.png/",
        color: "#187FB7"
    },
    {
        id: 23,
        name: "Kamakiri Togaru",
        alias: "Jack Mantis",
        class: "1-B",
        quirk: "Razor Sharp",
        birthday: "January 7",
        gender: "Male",
        fightingStyle: "Close Range Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/b/ba/Togaru_Kamakiri_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/b/ba/Togaru_Kamakiri_Anime_Profile.png/",
        color: "#9CD36E"
    },
    {
        id: 24,
        name: "Kuroiro Shihai",
        alias: "Vantablack",
        class: "1-B",
        quirk: "Black",
        birthday: "November 1",
        gender: "Male",
        fightingStyle: "Melee + Support Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/5/51/Shihai_Kuroiro_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/5/51/Shihai_Kuroiro_Anime_Profile.png/",
        color: "#252525"
    },
    {
        id: 25,
        name: "Kendo Itsuka",
        alias: "Battle Fist",
        class: "1-B",
        quirk: "Big Fist",
        birthday: "September 9",
        gender: "Female",
        fightingStyle: "Close Range Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/c/ca/Itsuka_Kendo_Full_Body_Hero_Costume.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/13/Itsuka_Kendo_Anime_Profile.png/",
        color: "#F59D00"
    },
    {
        id: 26,
        name: "Kodai Yui",
        alias: "Rule",
        class: "1-B",
        quirk: "Size",
        birthday: "December 19",
        gender: "Female",
        fightingStyle: "Long-range combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/4/4f/Yui_Kodai_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/4/4f/Yui_Kodai_Anime_Profile.png/",
        color:"#FAD6D7"
    },
    {
        id: 27,
        name: "Komori Kinoko",
        alias: "Shemage",
        class: "1-B",
        quirk: "Mushroom",
        birthday: "December 2",
        gender: "Female",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/d/d8/Volume_21_Sleeve_Kinoko_Komori_Hero_Costume.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/b/b9/Kinoko_Komori_Anime_Profile.png/",
        color: "#FAD5B2"
    },
    {
        id: 28,
        name: "Shiozaki Ibara",
        alias: "Vine",
        class: "1-B",
        quirk: "Vines",
        birthday: "September 8",
        gender: "Female",
        fightingStyle: "Medium Range Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/1b/Ibara_Shiozaki_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/1b/Ibara_Shiozaki_Anime_Profile.png/",
        color: "#19B83A"
    },
    {
        id: 29,
        name: "Shishida Jurota",
        alias: "Gevaudan",
        class: "1-B",
        quirk: "Beast",
        birthday: "March 26",
        gender: "Male",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/1a/Jurota_Shishida_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/1a/Jurota_Shishida_Anime_Profile.png/",
        color: "#523823"
    },
    {
        id: 30,
        name: "Shoda Nirengeki",
        alias: "Mines",
        class: "1-B",
        quirk: "Twin Impact",
        birthday: "February 2",
        gender: "Male",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/8c/Nirengeki_Shouda_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/8c/Nirengeki_Shouda_Anime_Profile.png/",
        color: "#BDD4DC"
    },
    {
        id: 31,
        name: "Tsunotori Ponī",
        alias: "Ponī",
        class: "1-B",
        quirk: "Horn Cannon",
        birthday: "April 21",
        gender: "Female",
        fightingStyle: "Melee + Ranged Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/83/Pony_Tsunotori_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/83/Pony_Tsunotori_Anime_Profile.png/",
        color: "#F6D691"
    },
    {
        id: 32,
        name: "Tsuburaba Kosei",
        alias: "Tsuburaba Kosei",
        class: "1-B",
        quirk: "Solid Air",
        birthday: "May 19",
        gender: "Male",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/84/Kousei_Tsuburaba_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/84/Kousei_Tsuburaba_Anime_Profile.png/",
        color: "#00A0DE"
    },
    {
        id: 33,
        name: "Tetsutetsu Tetsutetsu",
        alias: "Real Steel",
        class: "1-B",
        quirk: "Steel",
        birthday: "October 16",
        gender: "Male",
        fightingStyle: "Melee Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/9/90/Tetsutetsu_Anime_Costume.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/10/Tetsutetsu_Tetsutetsu_Anime_Profile.png/",
        color: "#979799"
    },
    {
        id: 34,
        name: "Tokage Setsuna",
        alias: "Lizardy",
        class: "1-B",
        quirk: "Lizard Tail Splitter",
        birthday: "October 13",
        gender: "Female",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/5/59/Setsuna_Tokage_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/5/59/Setsuna_Tokage_Anime_Profile.png/",
        color: "#01724A"
    },
    {
        id: 35,
        name: "Fukidashi Manga",
        alias: "Comicman",
        class: "1-B",
        quirk: "Comic",
        birthday: "February 2",
        gender: "Male",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/1a/Manga_Fukidashi_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/1/1a/Manga_Fukidashi_Anime_Profile.png/",
        color: "#F9FBFC"
    },
    {
        id: 36,
        name: "Honenuki Juzo",
        alias: "Mudman",
        class: "1-B",
        quirk: "Softening",
        birthday: "June 20",
        gender: "Male",
        fightingStyle: "Long-Range Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/9/98/Juzo_Honenuki_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/9/98/Juzo_Honenuki_Anime_Profile.png/",
        color: "#BAB6AA"
    },
    {
        id: 37,
        name: "Bondo Kojiro",
        alias: "Plamo",
        class: "1-B",
        quirk: "Cemedine",
        birthday: "December 23",
        gender: "Male",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/8b/Kojiro_Bondo_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/8b/Kojiro_Bondo_Anime_Profile.png/",
        color: "#E3D285"
    },
    {
        id: 38,
        name: "Monoma Neito",
        alias: "Phantom Thief",
        class: "1-B",
        quirk: "Copy",
        birthday: "May 13",
        gender: "Male",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/b/b5/Neito_Monoma_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/b/b5/Neito_Monoma_Anime_Profile.png/",
        color: "#E0DB00"
    },
    {
        id: 39,
        name: "Yanagi Reiko",
        alias: "Emily",
        class: "1-B",
        quirk: "Poltergeist",
        birthday: "February 11",
        gender: "Female",
        fightingStyle: "Long-ranged fighter",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/8f/Reiko_Yanagi_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/8f/Reiko_Yanagi_Anime_Profile.png/",
        color: "#CCD2E7"
    },
    {
        id: 40,
        name: "Rin Hiryu",
        alias: "Dragon Shroud",
        class: "1-B",
        quirk: "Scales",
        birthday: "July 14",
        gender: "Male",
        fightingStyle: "Mixed Range Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/c/c0/Hiryuu_Rin_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/c/c0/Hiryuu_Rin_Anime_Profile.png/",
        color: "#015934"
    },
    {
        id: 41,
        name: "Togata Mirio",
        alias: "Lemillion",
        class: "3-B",
        quirk: "Permeation",
        birthday: "July 15",
        gender: "Male",
        fightingStyle: "Melee Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/a/aa/Mirio_Togata_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/6/62/Mirio_Togata_Anime.png/",
        color: "#EFC83A"
    },
    {
        id: 42,
        name: "Hado Nejire",
        alias: "Nejire-chan",
        class: "3-A",
        quirk: "Wave Motion",
        birthday: "October 6",
        gender: "Female",
        fightingStyle: "Ranged Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/a/a9/Nejire_Hado_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/9/97/Nejire_Hado_Anime.png/",
        color: "#6F97C7"
    },
    {
        id: 43,
        name: "Amajiki Tamaki",
        alias: "Suneater",
        class: "3-A",
        quirk: "Manifest",
        birthday: "March 4",
        gender: "Male",
        fightingStyle: "Melee + Support Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/d/d4/Tamaki_Amajiki_Hero_Costume_Anime_Action.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/8/83/Tamaki_Amajiki_Anime.png/",
        color: "#68687A"
    },
    {
        id: 44,
        name: "Shinso Hitoshi",
        alias: "Shinso Hitoshi",
        class: "1-C",
        quirk: "Brainwashing",
        birthday: "July 1",
        gender: "Male",
        fightingStyle: "Support Combat",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/9/92/Hitoshi_Shinsou_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/9/92/Hitoshi_Shinsou_Anime_Profile.png/",
        color: "#5E5C93"
    },
    {
        id: 45,
        name: "Hatsume Mei",
        alias: "Hatsume Mei",
        class: "1-H",
        quirk: "Zoom",
        birthday: "April 18",
        gender: "Female",
        fightingStyle: "???",
        image: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/c/c5/Mei_Hatsume_Anime_Profile.png/",
        imageSchool: "https://vignette.wikia.nocookie.net/bokunoheroacademia/images/c/c5/Mei_Hatsume_Anime_Profile.png/",
        color: "#ED9494"
    }
]

export default studentsData
